{% set version = "1.0.2" %}

package:
  name: glue-vispy-viewers
  version: {{version}}

source:
  fn: glue-vispy-viewers-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/glue-vispy-viewers-{{version}}.tar.gz
  sha256: 6e0fc7f0e0c1d62756953582830357dcccf8bc8f61ea0fb7613c08df91f59671

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  host:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python
    - numpy >=1.9
    - pyopengl
    - glue-core >=0.14
    - matplotlib
    - qtpy
    - scipy
    - astropy >=1.1
    - pyqt >=5.6,<6.0a0

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home:  http://glueviz.org
  license: BSD 3-Clause
  summary: 3D viewers for Glue
  dev_url: https://github.com/glue-viz/glue-vispy-viewers
  doc_url: http://glueviz.org/en/stable/gui_guide/3d_viewers.html

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
