{% set version = "1.0.5" %}

package:
  name: glue-vispy-viewers
  version: {{version}}

source:
  fn: glue-vispy-viewers-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/glue-vispy-viewers-{{version}}.tar.gz
  sha256: 9d126735b1c1b08a56e02e11d0eba20c040ff934c8d1fd6644e7ee085a420569

build:
  number: 0
  skip: True  # [py<37 or ppc64le or s390x]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  host:
    - python
    - setuptools
    - setuptools_scm
    - wheel

  run:
    - python
    - numpy
    - pyopengl
    - glue-core >=1.0
    - matplotlib-base
    - qtpy
    - scipy
    - astropy >=4.0
    - pillow
    - vispy >=0.6
    - pyqt >=5.9,<6.0a0

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume
  commands:
    - pip check
  requires:
    - pip

about:
  home:  https://glueviz.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 3D viewers for Glue
  description: 3D viewers for Glue using VisPy
  dev_url: https://github.com/glue-viz/glue-vispy-viewers
  doc_url: https://glueviz.org/en/stable/gui_guide/3d_viewers.html

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
  skip-lints:
    - missing_doc_source_url
    - missing_license_url
    - gui_app