{% set version = "0.9.1" %}

package:
  name: glue-vispy-viewers
  version: {{version}}

source:
  fn: glue-vispy-viewers-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/glue-vispy-viewers-{{version}}.tar.gz
  sha256: f9b17ada7f991a265635327c04545d9f1ab7960540fe3f30eaa77726208cb9d4

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  host:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.9
    - pyopengl
    - glue-core >=0.12
    - matplotlib
    - qtpy
    - scipy
    - astropy >=1.1
    - pyqt 4.11.*|5.6.*

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home:  http://glueviz.org
  license: BSD 3-Clause
  summary: 3D viewers for Glue
  dev_url: https://github.com/glue-viz/glue-vispy-viewers
  doc_url: http://glueviz.org/en/stable/gui_guide/3d_viewers.html

extra:
  recipe-maintainers:
    - astrofrog
