{% set name = "glue-vispy-viewers" %}
{% set version = "1.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{version}}.tar.gz
  sha256: aa9bc2b11d851ac1c12d953d4637b48b6eff9449f54715c92e654c38407af54a

build:
  number: 0
  skip: true  # [py<310]
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - numpy
    - pyopengl
    - glue-core >=1.13.1
    - echo >=0.6
    - scipy
    - matplotlib-base
    - vispy >=0.12.0
    - importlib-metadata
    - glfw
    - imageio
    - jupyter-rfb

test:
  # glue-vispy-viewers: glfw-backed imports; keep smoke tests only.
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://glueviz.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 3D viewers for Glue
  description: 3D viewers for Glue using VisPy
  dev_url: https://github.com/glue-viz/glue-vispy-viewers
  doc_url: https://glueviz.org/en/stable/gui_guide/3d_viewers.html

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
  skip-lints:
    - missing_doc_source_url
    - missing_license_url
    - gui_app
