{% set version = "0.9" %}

package:
  name: glue-vispy-viewers
  version: {{version}}

source:
  fn: glue-vispy-viewers-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/glue-vispy-viewers-{{version}}.tar.gz
  sha256: 8af81e184fc2ed43421f5be4affb88b9c190dd6c5ef14317821bd6b921c591d3

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pyopengl
    - glue-core >=0.12
    - matplotlib
    - qtpy
    - astropy >=1.1
    - pyqt 4.11.*|5.6.*

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD 3-Clause
  summary: 3D viewers for Glue

extra:
  recipe-maintainers:
    - astrofrog
