travis:
  secure:
    BINSTAR_TOKEN: qI65rSic+a2yUI9ChblcLvqKNjAx/p/urdB7XCOfKe+HKuZ8ykK0c8FTp0jJrSXm1qx9meTlmwKLFwQBYgwwgVG09qL0WkVrbTg+Fnht3A9L/wKwzp8p67US4heF3Fa7VqdaDKqDbmzcJt71HfkLfBdp4ETcZkr5jI7NvXVSvzc4//+vpTFiNSwfHyRzJkv9lRNOAu1f5R6hTOYvruvlVRTJYRPHxXPvfqMC/ezAzwZ++giSD4r/3ZHM+renGh6vdr/Th3gjDAcGcTQ20UeVaKJjSoGwRvIqHeneKnaeOBz2fWDDdmlcMpTG7BgE1FXZ99GfxEZs/0YKKOZfkjmOS59KukfbPyyBMXo7vTEVoJrH/WuZuDZJod2CKrYeAarr63j50jIFgtddKdZ7AurBzmkxBXAaRZ6O3Jjk+UTTJFEGz57tHrLRF1EUHr2u8PQNqhuU3e6jvR1bZlStP1l5EIUDZJ6dvX3JOEcQdjMmzO33fkFdPKhL+GKydTe914ph82rMh1gOYVZ9VW00jxcHux9myATFjZ8Nt0eacOtxhBChRSsmJQdJz+Ya8V7yk7U2M6A3hz0tgpEW6kDMAUQcf4+ANe4ETg7t9wyhKkD6cXq7CKZIRoiysGe3we4X8W/kk9zMAZBnIup/dj+MHsbJh6Ye/AhyGgERZzrR67szDK8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
