travis:
  secure:
    BINSTAR_TOKEN: SXjRN61Tsy6/mMtZWRX91OFY5pD/8s5mCfJ0Bo3GgDH0ITeHULdxTKt1Gy5KMjM0ikrBYv4ZLn6/S1afjVyoPQyvteuMpkI9fTyIlR+MRpZldvV9Q/K3mJ2ws1EEF+LlueFbueVCVcZzUphxvPsjmBJI00aFrW/pTO1H4sACv/N7KN9hOtb+9lyvynVM77pNB7QDKQgZER3Vw9BorBXqHY6mE5xEEE/G9jH4bXa4VTwn8YxGPqPMwRbHTaEbrThOQClqedLp9iS0T5zov5gYh0+UJYC0frmQyRc2FG2GbWO3DmzePgxJfvSnjQB09DfDWgu+RqvHwGSd7LmPwjI9ZpLU3YJxxEauyHlVKzCMq9ZuUUvdsRu3akp9LWWIYKKwAl/vkHX79RGlOfbQj/8Ch39wW1PURwqv2Ntlz78hUWsetDBvVLN5Ea+LvSFghY4DSOUg8DvtScDp2R92Gx/FsEYiqjGi0ahcWlmwF4mU80W33NTg+sLq4FBYeOyJLHt8kzw0gHwphUYA4leDcbgB0ucZPNYMRA5816xhQC/0J6PGLTl+M/9wsSFflRQSG/KyK4il4ZCxlCDCkGmCbby1sUQxeBjYPjePvUpRoukibE7yCiFmmvHaRsjiCt2vDtX1F+WsNA7dXcKeUdjWbmAH6V8CRolrF0s7xK7foOvgpl4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
